### PR TITLE
 Autofocus support on input change

### PR DESCRIPTION
**Pull request by tech-doctor**
**File Modified:** `OTPinput.tsx` located in the `src` folder (root directory).

 ### Changes Introduced:
I implemented autofocus functionality for the OTP input fields to improve user experience.

**Autofocus on Input Change:**
The `focusOnNext` function (defined on line 194) automatically shifts focus to the next input field once the current one is filled. This enhancement eliminates the need for users to manually move to the next input box.

**Integration with JSX:**
The `focusOnNext` function is integrated into the `onInput` attribute (on line 248) with appropriate arguments to manage the autofocus behavior dynamically.

This change simplifies the input process by making it more intuitive and seamless for users.

### CODE REVIEW

**Review by EOEboh — COMMENTED** [review]
I added this feature and it worked well on Storybook. Did you test the component and it wasn't working? 

If not, I will be happy to merge this change

**Comment by tech-doctor** [comment]
Yes. I noticed it worked well on storybook but on testing the component, it wasn't working.

**Comment by EOEboh** [comment]
Okay i ran the pull request locally and there's a slight TypeScript error with the event type of the `focusOnNext` function, (take a look at the image below). Please fix that so I can merge the changes. 

Screenshot (47)

**Comment by EOEboh** [comment]
For some reason, GitHub isn't showing images, but I hope you get it.

**Comment by tech-doctor** [comment]
Yea, I get where that is coming from. I'll get  it fixed in a moment.

**Comment by tech-doctor** [comment]
The typescript error has been resolved.  It seems fine from my end. You can check it out from your end and provide feedback.

**Comment by EOEboh** [comment]
Looks fine! Thank you

**Comment by EOEboh** [comment]
@all-contributors please add @tech-doctor for code

**Pull request merged**
