### PR TITLE
feat(demo): Interactive Demo Proposal #2

### LINKED ISSUE #2: Interactive Demo Proposal
## What's the idea?
Making an example interactive demo page for react-one-time-password. Creating a playground where devs can try out the package without installing it.

## Why is it needed?
1. Some devs aren't sure how the package works just by reading about it
2. Devs like to test things before they use them in their projects
3. It's hard to show all the cool features of the package in static README
4. A lot of questions can be answered by playing with the package

## How can we fix it?
Adding an interactive demo example that lets visitors:

1. Type in a custom one-time password
2. Change settings like timer duration or input style
3. See the component update in real-time
4. Copy the code for their custom setup

## Why is this good?
- Devs can understand the package better
- Devs can test if it fits their needs
- Fewer basic questions to answer
- It shows off all the cool things the package can do
- It might convince more people to use the package

### PR DESCRIPTION
**Pull request by xosnrdev**
>This pr resolves #2

# Preview
preview

### CODE REVIEW

**Review by struckchure — APPROVED** [review]

**Comment by EOEboh** [comment]
Nice work @xosnrdev 
Can you please explain how to use the demo?

**Comment by xosnrdev** [comment]
> Nice work @xosnrdev 
> 
> Can you please explain how to use the demo?
> 
> 

The demo lets you try out different settings for the `OTPInput` and see the changes instantly. It also shows the code for the current setup, which you can copy and use.

### How to use:
There are two main tabs:

1. **Preview Tab**:  
   You can change the `OTPInput` settings using the control panel, and the input will update right away.

2. **Code Tab**:  
   This shows the code for the current settings from the Preview tab. You can copy the code and use it in your project.

**Comment by EOEboh** [comment]
@xosnrdev While I fully understand what the PR is about, I would need you to write a step by step on how the demo can be utilized. 

Things like how to start the demo, where can it be run etc

**Comment by xosnrdev** [comment]
> @xosnrdev While I fully understand what the PR is about, I would need you to write a step by step on how the demo can be utilized. 
> 
> 
> 
> Things like how to start the demo, where can it be run etc

There's no need to start anything here. This demo is just an example of how to use the library, similar to what you'd find with most libraries on NPM. They provide an interactive web page where you can explore and learn more about the library and its API. It could be hosted on GitHub Pages or Cloudflare Pages and linked in the README for easy access.

Example reference: https://uiwjs.github.io/react-split/

I can see you've published a new version I'll update the demo `types/index.ts`

**Comment by xosnrdev** [comment]
Oh nevermind you already made your example I just saw it now

**Comment by xosnrdev** [comment]
I'll be closing shortly

**Pull request closed without merging**
